# Generated by Django 5.1.7 on 2025-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('busy', 'Busy'), ('away', 'Away')], default='available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
