# Generated by Django 5.1.7 on 2025-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('away', 'Away')], default='available', max_length=20),
        ),
    ]
