# Generated by Django 5.1.7 on 2025-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('progress_updated', 'Progress Updated'), ('task_completed', 'Task Completed')], max_length=30),
        ),
    ]
