# Generated by Django 5.1.7 on 2025-04-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskassignment_taskcomment_taskprogress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
