# Generated by Django 5.1.7 on 2025-04-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_useractivity_activity_type'),
        ('tasks', '0004_remove_chatbot_tables'),
    ]

    operations = [
    ]
